# docker-compose.yml (исправленный)
version: "3.9"

services:
  barkery_bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./backups:/app/backups  # Для хранения резервных копий
      - ./barkery.db:/app/barkery.db  # Для сохранения БД
    restart: always