version: '3.8'

services:
  barkery-bot:
    build: .
    container_name: barkery-bot
    restart: unless-stopped
    volumes:
      - ./data:/home/barkery/app/data
      - ./backups:/home/barkery/app/backups
      - ./logs:/home/barkery/app/logs
    env_file:
      - .env.production
    environment:
      - TZ=Europe/Belgrade
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"